### PR TITLE
LaTeX in MarkDown

### PR DESCRIPTION
**Pull request by pearu**

### CODE REVIEW

**Comment by mattip** [comment]
Is this based on https://github.com/leegao/readme2tex ?

**Comment by pearu** [comment]
> Is this based on https://github.com/leegao/readme2tex ?

No, but thanks for sharing this project!
Here the LaTeX rendering is done on the fly but I'll check if readme2tex resolves my problem.

**Comment by pearu** [comment]
@mattip,  I looked into readme2tex: it basically renders latex expression with pdflatex (locally) and provides convenient hooks to store the generated images in github (in a specialized branch of the repo).

Compared to this PR, here we render latex expressions with an online service, so no need to deal with committing generated image (although, to make the MD document independent of the online service (that may stop serving at some point, for instance), having the generated images in the repo is an advantage).

Using the online rendering service has an advantage in that there will be one MD document. readme2tex approach requires dealing with input and output MD documents. I am not sure if the output MD documents can be edited by another user, for instance, because the input documents are not committed to the repo.

Even when using the online rendering service, it seems that github does automatic caching of the rendered images already.

So, I see that this PR might still have a value :)

**Comment by mattip** [comment]
Thanks, makes sense.

**Pull request merged**
